### ISSUE TITLE
Base UI wireframe and Requirements 

### ISSUE THREAD

**Issue by mahdikhashan** [boudicca-events/boudicca.events-publisher-native-android#1]
compare different designs on dribble and generate a base wireframe for the app with the below features:

1. list events
2. search inside events
3. filter events
4. unlimited scroll
5. consider accessibility

**Comment by mahdikhashan** [comment]
I have created a set of wireframes by pen and paper for main and event screens.

## Screens

### Main Screen

elements: 
- city selector dropdown
- search input
- category horizontal scrollable view
- upcoming events horizontal scrollable view
- event organizers grid view

#### Actions

1. the user can filter the events respective to the city he/she reside in by tapping on the dropdown and setting the current city. the current city will then be stored on device as a user preference and will be used every time the application starts.
2. the user can tap on the input search field and a modal will pop up which he/she can type and search between "event.name" and "event.description". the result will be shown to him/her in the modal and he/she can tap on a result then the respective event screen will be opened.
3. the user can tap on any of the categories in the horizontally scrollable view and redirect to the respective list of events for that category.
4. the user can tap on any of the event organizers items and redirect to the respective list of events for that organizer.
5. the bottom navigation bar is visible to the user and he/she can select between "home" and "bookmarked event" screens. 

#### Wireframes
![main-screen](https://github.com/boudicca-events/boudicca.events-publisher-native-android/assets/58775404/fe8470fa-5a16-4223-9944-2d0149a58b83)

### Event Screen

elements:
- bookmark action button
- share event action button
- event image
- event name text
- event data and time view
- event address view
- event organizer view
- event description
- event url fixed button

#### Actions

1. the user can bookmark the current event by tapping on the bookmark button in the topbar.
2. the user can share the event by tapping on the share button in the topbar.
3. the user can add the event to his/her device calendar by tapping on the "event data and time view".
4. the user can open the list of event for the current event organizer by tapping on the "event organizer view".
5. the user can fold/unfold the event description by tapping on a link at the bottom of the description.
7. the user can redirect to the event url by tapping on the fixed "event url button" at the bottom of the screen.

#### Wireframes
![event-screen-2](https://github.com/boudicca-events/boudicca.events-publisher-native-android/assets/58775404/6c19f37e-5071-4dd8-a2a9-ffe753633adf)
![event-screen](https://github.com/boudicca-events/boudicca.events-publisher-native-android/assets/58775404/56de5f45-438f-4362-a26b-d6255ec73c04)

### UI Design Inspirations

![inspiration-3](https://github.com/boudicca-events/boudicca.events-publisher-native-android/assets/58775404/31454ad1-8338-4989-8195-e4254ee4ef3a)
![inspiration-2](https://github.com/boudicca-events/boudicca.events-publisher-native-android/assets/58775404/5049c7a8-53c2-4766-9a5f-1581c0b9b4a6)
![inspiration-1](https://github.com/boudicca-events/boudicca.events-publisher-native-android/assets/58775404/6d88cd07-be5f-4d70-bdc5-7e31f1aca741)

**Comment by kadhonn** [comment]
hey!
sorry for the late reply.

in general i like the design, but it seems like a lot of work :D 

there is only one thing which i am unsure about: "the user can open the list of event for the current event organizer by tapping on the "event organizer view"."
 we do not have data for a event organizer. we only know locations

**Comment by mahdikhashan** [comment]
hey @kadhonn, no worries and thanks for your time.

yes, I agree with you, it's more than required for a course project, I'll refine some parts and make them fit within the timeframe. Then, I'll identify and create issues for future development.

also, now I know about the event organizer, I'll remove it from the design. however, I was thinking of using filter, not sure if it's possible for this use case.

Thanks for bringing this to my attention.

**Comment by kadhonn** [comment]
to filter for event organizers? this will also not be possible because we simply do not know the event organizer
